apiVersion: v1
kind: Service
metadata:
  name: bankscrappernodebalancer-service
  labels:
    app: bankScrapper
spec:
  type: LoadBalancer
  selector:
    app: bankscrapper
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
